language: scala

sudo: required

scala:
  - "2.11.12"
  - "2.12.7"

jdk:
  - oraclejdk8

dist: trusty

deploy:
  provider: script
  script:
    - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true
    repo: Tecsisa/lightQL

env:
  global:
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: "bcHxIH0FDCz1uhHpsnjQ1/Cd55lJUiQivLz7xXIrfsmBbdqiqcbuBvnXRvoMqKWv4reFQiNClwwLZMtDSzDqLuQSxIApsG9pyUhzaRBOEUSK9SxUsYDSv2qjSikAjvWLHk5CgBYQ1iQhSfu9V8C2tyu7ciUFBoO5I8RiRW9VY4ARX3MTz05+pouJSetMTz/U+BlmGb5/cXrOjG5mOCxx5ucQmaxUIIiDIjoPdCjxg0cnMOMizHs54NoXvITImuEPm3QpoATdRL4vPacbL7qkSXeW76oiK30GDkCTR0N5w2tcZT00/iRR7xb8Tryb05atxPxKFbfY9Zx1n+3HIuvB9N6+pjvrJytWUgcD3rfe90LpxkFlEoGgwxq1GBS3ZKl8oJYaUWBEy3X8W8vG8j9OZ13F1Oj4XbRMwpEe6TC2rC+Kf4bAR0yj+UQfEsvT+bP8KAgWJlD0URphnlr6/4vQg1Q30n4/EerY/REJ4E9Vshw/yYWn6GtG8CMFJYUBpM8BaBQKPGvgtk2WPNx4pfUBJzaFKTH+5gUS4n5rYweWXZi9Pj8K04GHXij41FM4ewbwimIfSJBAKM1XMBMU3vAGZH6VlLd7F+EAhdlPKegeouGa9kzh6m4+w09GWLi7zxQeY4+YIj5ulLx2oRpHExwtrQTTf3s3kztdv+yMXgR6q8s="
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "gsROLPYDwIDh5Mwa+LF0aeTPdvdPX3BSwlC3sB5vGDJxxWrYW+U7er3Ds8goAmexgwAp1HovCJtOuIEeo57XnauOPOmTpKvmWTg6TETMp/vkFJWWndQlpUs0+yc5GE3QDh6yYw3Zh+fPYLhMxyrYk3r7wv/PGPqnaqwyZ8OnB+8E7IXTsL1T5CDgyc4DUNz4BwPHxD2r7lF5zh31Fqn5/+1HW0BnW0ne3ERx+KK03vwF7soGfzcYBPDH17cv+a2kSaenOBe6sc6idcujTecEsA/kH3q+RV0RkKH2zksc3WJdfIURdhjGKL1Vit2cbQe0HIKWcOrpfHhnAtzjvnAaLzSYTFDU4ysZmGBGWDLLsM6C4mOIH8Iqfr0Tfo862MODqqKc5XFCvStaNH8dCZ+9lAOVh5Gnf5sUL6WshOkFk19mniKbeYLyl31HYLXKqLlXPi5cLFJDqs4RxDJoy+XQxqsuBHwQ5K+2P7jh7pRKpJvSNsIwATRjc3Dma60mAmtOr4+F6ZXFWIECPngYr5Vmwpw9moWaR2ArNKYH7VZqEobMgWrPOg2YImjU3rmcnjxIw75JVnlas1o4sWkLbSPGUEr55oNQ/Vj1ECIZRdWTn3zYKRlMOr2sJP7PyB912mECRe9i9m/21/gZOS81pxqL2LuxYVlZ6gmNx+G9tJAvhmM="

before_script:
  - sudo chmod +x /usr/local/bin/sbt

before_install:
- docker run -d -p 9200:9200 -p 9300:9300 -e "path.repo=/tmp" -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.7.2