language: scala

sudo: required

scala:
  - "2.13.4"
  - "2.12.13"

jdk:
  - oraclejdk8

dist: trusty

script:
  - sbt clean test elastic6-http/it:test elastic-http/it:test

before_script:
 - sudo chmod +x /usr/local/bin/sbt
