addSbtPlugin("de.heikoseeberger" %  "sbt-header"     % "3.0.2")
addSbtPlugin("com.lucidchart"    %  "sbt-scalafmt"   % "1.12")
addSbtPlugin("org.foundweekends" %  "sbt-bintray"    % "0.5.1")
addSbtPlugin("com.jsuereth"      %  "sbt-pgp"        % "1.1.0")
addSbtPlugin("com.47deg"         %  "sbt-microsites" % "0.7.4")
addSbtPlugin("com.eed3si9n"      %  "sbt-unidoc"     % "0.4.1")