addSbtPlugin("de.heikoseeberger" %  "sbt-header"     % "5.0.0")
addSbtPlugin("com.lucidchart"    %  "sbt-scalafmt"   % "1.15")
addSbtPlugin("org.foundweekends" %  "sbt-bintray"    % "0.5.4")
addSbtPlugin("com.jsuereth"      %  "sbt-pgp"        % "1.1.1")
addSbtPlugin("com.47deg"         %  "sbt-microsites" % "0.7.18")
addSbtPlugin("com.eed3si9n"      %  "sbt-unidoc"     % "0.4.1")