addSbtPlugin("de.heikoseeberger" %  "sbt-header"     % "5.6.0")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "1.5.1")
addSbtPlugin("org.foundweekends" %  "sbt-bintray"    % "0.6.1")
addSbtPlugin("com.jsuereth"      %  "sbt-pgp"        % "1.1.2")
addSbtPlugin("com.47deg"         %  "sbt-microsites" % "1.2.1")
addSbtPlugin("com.eed3si9n"      %  "sbt-unidoc"     % "0.4.3")